// Student Records module — per-student documents.
// 4 are admin-uploaded PDFs; 3 (course_confirmation, weekly_schedule,
// edmentum_credentials) are SIS-generated from an admin-entered form.

export type StudentRecordType =
  | 'math_diagnostic'
  | 'ela_diagnostic'
  | 'reading_diagnostic'
  | 'psychometric'
  | 'course_confirmation'
  | 'weekly_schedule'
  | 'edmentum_credentials'
  | 'assessment_instructions'

export type StudentRecordSource = 'upload' | 'generated'
export type StudentRecordStatus = 'pending' | 'available' | 'coming_soon'

export interface StudentRecord {
  id: string
  studentId: string
  recordType: StudentRecordType
  source: StudentRecordSource
  status: StudentRecordStatus
  storagePath: string | null
  fileName: string | null
  fileSize: number | null
  mimeType: string
  data: Record<string, unknown> | null
  uploadedBy: string | null
  uploadedAt: string | null
  generatedAt: string | null
}

export interface StudentRecordDef {
  type: StudentRecordType
  label: string
  source: StudentRecordSource
  description: string
}

// Display order: the 4 uploadable reports first (actionable for admins), then
// the 2 generated documents.
export const STUDENT_RECORD_DEFS: StudentRecordDef[] = [
  {
    type: 'math_diagnostic',
    label: 'Math Diagnostic Report',
    source: 'upload',
    description: 'Diagnostic assessment results for Mathematics.',
  },
  {
    type: 'ela_diagnostic',
    label: 'English Language Arts Diagnostic Report',
    source: 'upload',
    description: 'Diagnostic assessment results for English Language Arts.',
  },
  {
    type: 'reading_diagnostic',
    label: 'Reading Diagnostic Report',
    source: 'upload',
    description: 'Diagnostic assessment results for Reading.',
  },
  {
    type: 'psychometric',
    label: 'Psychometric Assessment Report',
    source: 'upload',
    description: 'Results of the guided online psychometric assessment.',
  },
  {
    type: 'course_confirmation',
    label: 'Course Confirmation',
    source: 'generated',
    description: 'Generated by the SIS from the confirmed subject selection.',
  },
  {
    type: 'weekly_schedule',
    label: 'Weekly Schedule',
    source: 'generated',
    description: 'Generated by the SIS from the student’s timetable blocks.',
  },
  {
    type: 'edmentum_credentials',
    label: 'Edmentum Courseware Portal',
    source: 'generated',
    description: 'Edmentum login credentials for online-programme students.',
  },
  {
    type: 'assessment_instructions',
    label: 'Assessment Instructions',
    source: 'generated',
    description: 'Psychometric assessment instructions and Bodhi login details.',
  },
]

export const STUDENT_RECORD_LABELS: Record<StudentRecordType, string> = Object.fromEntries(
  STUDENT_RECORD_DEFS.map(d => [d.type, d.label]),
) as Record<StudentRecordType, string>

export const MAX_RECORD_FILE_BYTES = 10 * 1024 * 1024 // 10 MB

export function sanitizeRecordFileName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/-+/g, '-')
}

export function rowToStudentRecord(r: Record<string, unknown>): StudentRecord {
  return {
    id: r.id as string,
    studentId: (r.student_id as string) ?? '',
    recordType: r.record_type as StudentRecordType,
    source: ((r.source as string) ?? 'upload') as StudentRecordSource,
    status: ((r.status as string) ?? 'pending') as StudentRecordStatus,
    storagePath: (r.storage_path as string | null) ?? null,
    fileName: (r.file_name as string | null) ?? null,
    fileSize: r.file_size == null ? null : Number(r.file_size),
    mimeType: (r.mime_type as string) ?? 'application/pdf',
    data: (r.data as Record<string, unknown> | null) ?? null,
    uploadedBy: (r.uploaded_by as string | null) ?? null,
    uploadedAt: (r.uploaded_at as string | null) ?? null,
    generatedAt: (r.generated_at as string | null) ?? null,
  }
}

export function formatFileSize(bytes: number | null | undefined): string {
  if (!bytes || bytes <= 0) return ''
  if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
